### ISSUE TITLE
Error during running "make build"

### ISSUE THREAD

**Issue by ensiehaliagha** [pku-dasys/pillars#3]
Hello,
I installed all the necessary packages for pillars. (I installed them on ubuntu 18.04 ) when I run "make build" I get the error "Object Gurobi is not a member of package root". I do not know how I can resolve it. It is great if anyone can help me to solve this error.

Best Regards,
Ensieh[](url)

**Comment by g478227411** [comment]
Hello,
If you have correctly installed Gurobi, acquired the license and set environmental variables, you should be able to run Gurobi in terminal. Please check everything about Gurobi first. If there is no error, maybe you can try to use IDEA IntelliJ 2019.2 to run pillars, and use "add library" to add package of Gurobi.

Best Regards,
Yijiang Guo

**Comment by ensiehaliagha** [comment]
Thanks a lot. I will check Gurobi environmental variable and license again.

Sincerely yours,
Ensieh
