### ISSUE TITLE
ApplicationsExamples.scala ->chisel3.Driver.execute

### ISSUE THREAD

**Issue by JiawenDeng** [pku-dasys/pillars#5]
"chisel-iotesters is end-of-life. Use chiseltest instead“
![image](https://user-images.githubusercontent.com/89446537/170913102-301f7110-9de4-4a5e-9eb5-6fa22b1200c2.png)

**Comment by g478227411** [comment]
Thank you for your question.
It maybe the version compatibility of chisel.
We use chisel v3.2 in our project, where 
chisel-iotesters are the verification infrastructures.
But it's replaced be chiseltest in new version of chisel (>=v3.4).
So maybe you can check whether the chisel version is correct, or try to use chiseltest instead. 

Best Regards,
Yijiang Guo

**Comment by luoguojie** [comment]
The code has been upgraded for chisel 3.5.6 and chiseltest 0.5.6 after commit [ad1ecfe4c571000a6da6325db9df3678f35741a0](https://github.com/pku-dasys/pillars/commit/ad1ecfe4c571000a6da6325db9df3678f35741a0).
