### ISSUE TITLE
error in the  'make run' command 

### ISSUE THREAD

**Issue by muse-coder** [pku-dasys/pillars#6]
I followed the markdown ,then downloaded and installed the relevant dependencies correctly.
I succucessfully  run the 'make build' command 
but there were some warnings like ''[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list''
then error occured when I run the ''make run''command as followed
![image](https://user-images.githubusercontent.com/65820305/177108421-acc79a21-c70c-48b7-85d6-5bffd36c7d56.png)
![image](https://user-images.githubusercontent.com/65820305/177108656-94ab6a36-909c-4bd5-897a-43c79ab9e0e6.png)
The error seems to come during the verilator startup phase, I tried retrieving it but don't know what went wrong. I don't know if it's because of the version compatibility.
the dependencies packages version   I used is
verilator == 4.038   

so could you please tell me  what I should do to fix the error?

**Comment by g478227411** [comment]
Thank you for your question.
It maybe the version compatibility of verilator.
You can try the old version (v3.916) which we used, or the latest version (>=  v4.102).
You can refer to the issue of chisel [https://github.com/chipsalliance/chisel3/issues/1565](url).

Best Regards,
Yijiang Guo

**Comment by muse-coder** [comment]
you‘re right,I updated the version,then the pillars could successfully run.Thanks for your suggestion.
